pipeline {
    agent { node { label 'Agent' } } 

    stages {
        stage('Init') {
            steps {
                sh '''
                    terraform init
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                    terraform plan
                '''
            }
        }
        stage('Deploy') {
            steps {
                input 'Shall I apply'
            }
        }
         stage('Deploy') {
            steps {
                sh '''
                    terraform apply -auto-approve
                '''
            }
        }
    }

    post { 
        always { 
            echo 'I will always say whether the job is success or not'
        }
        success{
            echo 'I will only run when the job is success'
        }
        failure{
            echo 'I will only run when the job is failure'
        }
    }
}